/**
 * TODO
 * - [Demo Shop Login] must be replaced with LINE login
 * - Add [LINE Login] button with this guidelines https://developers.line.biz/en/docs/line-login/login-button/#design-guidelines
 */
import type { NextPage } from "next";
// import Head from 'next/head'
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";
import { useSession, signIn, signOut } from "next-auth/react";
import Link from "next/link";

const IndexPage: NextPage = () => {
  const { data, status } = useSession();
  console.log("useSession", useSession());
  // const { data: { user } } = useSession();
  const demoSignIn = () => {
    signIn("credentials", {
      callbackUrl: "/Home",
      user: "john",
      password: "123456",
    });
  };

  const signInWithLine = () => {
    signIn("line", { callbackUrl: "/Home" });
  };
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          {/* Welcome {user.name} */}
          Default Landing Page
        </h1>

        <div>{status}</div>
        {status !== "authenticated" ? (
          <>
            <Button
              onClick={demoSignIn}
              variant="contained"
              color="success"
              className="text-dark hover:text-white w-60"
            >
              DEMO SHOP LOGIN
            </Button>
            <Button
              onClick={signInWithLine}
              variant="contained"
              color="success"
              className="text-dark hover:text-white w-60"
            >
              Sign In with LINE
            </Button>
          </>
        ) : (
          <>
            <Image src={data.user?.image as string} width={80} height={80} />
            <span>Welcome {data.user?.name as string}</span>
            <Link href="/Logo">
              <Button
                variant="contained"
                color="success"
                className="text-dark hover:text-white w-60"
              >
                Go to Shop
              </Button>
            </Link>
            <Link href="/mc">
              <Button
                variant="contained"
                color="warning"
                className="text-dark hover:text-white w-60"
              >
                Management Console
              </Button>
            </Link>
            <Button
              variant="contained"
              color="error"
              className="text-dark hover:text-white w-60"
              onClick={() => {
                throw new Error("Sentry Frontend Error");
              }}
            >
              Sentry Test Throw error
            </Button>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://rehatcher.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/logo-rehatcher.png"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
  // @ts-ignore
  IndexPage.auth = false;
};
export default IndexPage;
